"""RTL export: the polar-DPD dual LUT as synthesizable Verilog.

The AM-AM inverse and AM-PM correction LUTs are the polar TX's
signature digital block.  Export quantizes them to hardware formats
(unsigned amplitude, signed phase in pi-scaled two's complement),
emits a $readmemh ROM module + a self-checking testbench, and writes
golden vectors from the bit-true Python quantization — the pllsim
export convention: RTL verified against Python at zero tolerance
(iverilog, skipped when unavailable).
"""
from __future__ import annotations

import os

import numpy as np


def quantize_dpd_luts(dpd, *, addr_bits: int = 8, amp_bits: int = 12,
                      ph_bits: int = 14) -> dict:
    """Sample the PolarDPD LUTs on a 2^addr_bits grid and quantize.

    amp: unsigned, full scale = (2^amp_bits - 1).
    phase: signed two's complement, [-pi, pi) mapped to the full range.
    """
    n = 1 << addr_bits
    x = np.arange(n) / (n - 1)
    amp, ph = dpd.predistort(x)
    amp_code = np.clip(np.rint(amp * ((1 << amp_bits) - 1)),
                       0, (1 << amp_bits) - 1).astype(np.int64)
    half = 1 << (ph_bits - 1)
    ph_code = np.clip(np.rint(ph / np.pi * half), -half, half - 1
                      ).astype(np.int64)
    return {"addr_bits": addr_bits, "amp_bits": amp_bits,
            "ph_bits": ph_bits, "amp_code": amp_code, "ph_code": ph_code,
            "amp_float": amp_code / ((1 << amp_bits) - 1),
            "ph_float": ph_code * np.pi / half}


def emit_dpd_rtl(luts: dict, outdir: str) -> dict:
    """Write polar_dpd_lut.v, ROM .memh files, golden CSV, testbench."""
    os.makedirs(outdir, exist_ok=True)
    ab, gb, pb = luts["addr_bits"], luts["amp_bits"], luts["ph_bits"]
    n = 1 << ab
    paths = {}

    def _w(name, text):
        p = os.path.join(outdir, name)
        with open(p, "w") as f:
            f.write(text)
        paths[name] = p

    amp_hex = "\n".join(f"{c:0{(gb + 3) // 4}x}" for c in luts["amp_code"])
    ph_hex = "\n".join(f"{c & ((1 << pb) - 1):0{(pb + 3) // 4}x}"
                       for c in luts["ph_code"])
    _w("dpd_amp.memh", amp_hex + "\n")
    _w("dpd_ph.memh", ph_hex + "\n")

    _w("polar_dpd_lut.v", f"""// polar DPD dual LUT (generated by polartx.export.rtl)
// addr: envelope command [{ab}b] -> amp: predistorted DPA code [{gb}b],
//                                   ph:  AM-PM correction [{pb}b signed, pi-scaled]
module polar_dpd_lut (
    input  wire              clk,
    input  wire [{ab - 1}:0] addr,
    output reg  [{gb - 1}:0] amp,
    output reg  signed [{pb - 1}:0] ph
);
    reg [{gb - 1}:0] rom_amp [0:{n - 1}];
    reg [{pb - 1}:0] rom_ph  [0:{n - 1}];
    initial begin
        $readmemh("dpd_amp.memh", rom_amp);
        $readmemh("dpd_ph.memh", rom_ph);
    end
    always @(posedge clk) begin
        amp <= rom_amp[addr];
        ph  <= $signed(rom_ph[addr]);
    end
endmodule
""")

    golden = "\n".join(f"{i},{a},{p}" for i, (a, p) in
                       enumerate(zip(luts["amp_code"], luts["ph_code"])))
    _w("golden_dpd.csv", golden + "\n")

    _w("tb_polar_dpd_lut.v", f"""// self-checking testbench: sweeps every address, compares to golden CSV
`timescale 1ns/1ps
module tb_polar_dpd_lut;
    reg clk = 0;
    reg [{ab - 1}:0] addr = 0;
    wire [{gb - 1}:0] amp;
    wire signed [{pb - 1}:0] ph;
    polar_dpd_lut dut(.clk(clk), .addr(addr), .amp(amp), .ph(ph));

    integer fd, code, ga, gp, gi, errors, i, r;
    initial begin
        errors = 0;
        fd = $fopen("golden_dpd.csv", "r");
        if (fd == 0) begin $display("FAIL: no golden file"); $finish; end
        for (i = 0; i < {n}; i = i + 1) begin
            r = $fscanf(fd, "%d,%d,%d\\n", gi, ga, gp);
            addr = gi[{ab - 1}:0];
            #1 clk = 1; #1 clk = 0;   // one clock edge
            if (amp !== ga[{gb - 1}:0] || ph !== gp[{pb - 1}:0])
                begin errors = errors + 1;
                $display("MISMATCH @%0d: amp %0d/%0d ph %0d/%0d",
                         gi, amp, ga, ph, gp); end
        end
        if (errors == 0) $display("PASS: {n} vectors, zero mismatches");
        else $display("FAIL: %0d mismatches", errors);
        $finish;
    end
endmodule
""")
    return paths


def efm1_int_golden(phase_words: np.ndarray, n_bits: int,
                    frac_bits: int) -> np.ndarray:
    """Bit-true integer reference of the first-order error-feedback
    quantizer: s = x + err; code = (s >> frac) mod 2^n; err = s & mask."""
    mask = (1 << frac_bits) - 1
    nmod = (1 << n_bits) - 1
    err, out = 0, np.empty(len(phase_words), dtype=np.int64)
    for i, x in enumerate(np.asarray(phase_words, dtype=np.int64)):
        s = int(x) + err
        out[i] = (s >> frac_bits) & nmod
        err = s & mask
    return out


def emit_dtc_dither_rtl(outdir: str, *, n_bits: int = 11,
                        frac_bits: int = 8, n_vec: int = 2048,
                        seed: int = 7) -> dict:
    """DTC code path: phase word -> EFM1-dithered DTC code (sequential
    logic; golden vectors stepped clock-by-clock)."""
    os.makedirs(outdir, exist_ok=True)
    w = n_bits + frac_bits
    rng = np.random.default_rng(seed)
    xw = rng.integers(0, 1 << w, n_vec)
    golden = efm1_int_golden(xw, n_bits, frac_bits)
    paths = {}

    def _w(name, text):
        p = os.path.join(outdir, name)
        with open(p, "w") as f:
            f.write(text)
        paths[name] = p

    _w("dtc_dither.v", f"""// DTC EFM1 dither code path (generated by polartx.export.rtl)
// phase word [{w}b] = code[{n_bits}b].frac[{frac_bits}b] -> dithered DTC code
module dtc_dither (
    input  wire              clk,
    input  wire              rst,
    input  wire [{w - 1}:0]  phase_w,
    output wire [{n_bits - 1}:0] code
);
    reg [{frac_bits - 1}:0] err;
    wire [{w}:0] s = phase_w + err;
    assign code = s[{w - 1}:{frac_bits}];   // mod 2^{n_bits} by truncation
    always @(posedge clk)
        if (rst) err <= 0;
        else     err <= s[{frac_bits - 1}:0];
endmodule
""")
    _w("golden_dither.csv",
       "\n".join(f"{x},{g}" for x, g in zip(xw, golden)) + "\n")
    _w("tb_dtc_dither.v", f"""`timescale 1ns/1ps
module tb_dtc_dither;
    reg clk = 0, rst = 1;
    reg [{w - 1}:0] phase_w = 0;
    wire [{n_bits - 1}:0] code;
    dtc_dither dut(.clk(clk), .rst(rst), .phase_w(phase_w), .code(code));
    integer fd, gx, gc, errors, i, r;
    initial begin
        errors = 0;
        fd = $fopen("golden_dither.csv", "r");
        if (fd == 0) begin $display("FAIL: no golden file"); $finish; end
        #1 clk = 1; #1 clk = 0; rst = 0;   // reset err
        for (i = 0; i < {n_vec}; i = i + 1) begin
            r = $fscanf(fd, "%d,%d\\n", gx, gc);
            phase_w = gx[{w - 1}:0];
            #1;                             // combinational code settles
            if (code !== gc[{n_bits - 1}:0]) begin
                errors = errors + 1;
                $display("MISMATCH @%0d: %0d/%0d", i, code, gc);
            end
            #1 clk = 1; #1 clk = 0;         // register err for next word
        end
        if (errors == 0) $display("PASS: {n_vec} vectors, zero mismatches");
        else $display("FAIL: %0d mismatches", errors);
        $finish;
    end
endmodule
""")
    return paths


def verify_dither_with_iverilog(outdir: str) -> str | None:
    import shutil
    import subprocess
    if shutil.which("iverilog") is None:
        return None
    vvp = os.path.join(outdir, "tb_dither.vvp")
    subprocess.run(["iverilog", "-o", vvp, "dtc_dither.v",
                    "tb_dtc_dither.v"], cwd=outdir, check=True)
    out = subprocess.run(["vvp", os.path.basename(vvp)], cwd=outdir,
                         check=True, capture_output=True, text=True)
    return out.stdout


def verify_with_iverilog(outdir: str) -> str | None:
    """Compile + run the testbench; returns stdout, or None when
    iverilog is not installed."""
    import shutil
    import subprocess
    if shutil.which("iverilog") is None:
        return None
    vvp = os.path.join(outdir, "tb.vvp")
    subprocess.run(["iverilog", "-o", vvp, "polar_dpd_lut.v",
                    "tb_polar_dpd_lut.v"], cwd=outdir, check=True)
    out = subprocess.run(["vvp", os.path.basename(vvp)], cwd=outdir,
                         check=True, capture_output=True, text=True)
    return out.stdout
