"""RTL export: the polar-DPD dual LUT as synthesizable Verilog.

The AM-AM inverse and AM-PM correction LUTs are the polar TX's
signature digital block.  Export quantizes them to hardware formats
(unsigned amplitude, signed phase in pi-scaled two's complement),
emits a $readmemh ROM module + a self-checking testbench, and writes
golden vectors from the bit-true Python quantization — the pllsim
export convention: RTL verified against Python at zero tolerance
(iverilog, skipped when unavailable).
"""
from __future__ import annotations

import os

import numpy as np


def quantize_dpd_luts(dpd, *, addr_bits: int = 8, amp_bits: int = 12,
                      ph_bits: int = 14) -> dict:
    """Sample the PolarDPD LUTs on a 2^addr_bits grid and quantize.

    amp: unsigned, full scale = (2^amp_bits - 1).
    phase: signed two's complement, [-pi, pi) mapped to the full range.
    """
    n = 1 << addr_bits
    x = np.arange(n) / (n - 1)
    amp, ph = dpd.predistort(x)
    amp_code = np.clip(np.rint(amp * ((1 << amp_bits) - 1)),
                       0, (1 << amp_bits) - 1).astype(np.int64)
    half = 1 << (ph_bits - 1)
    ph_code = np.clip(np.rint(ph / np.pi * half), -half, half - 1
                      ).astype(np.int64)
    return {"addr_bits": addr_bits, "amp_bits": amp_bits,
            "ph_bits": ph_bits, "amp_code": amp_code, "ph_code": ph_code,
            "amp_float": amp_code / ((1 << amp_bits) - 1),
            "ph_float": ph_code * np.pi / half}


def emit_dpd_rtl(luts: dict, outdir: str) -> dict:
    """Write polar_dpd_lut.v, ROM .memh files, golden CSV, testbench."""
    os.makedirs(outdir, exist_ok=True)
    ab, gb, pb = luts["addr_bits"], luts["amp_bits"], luts["ph_bits"]
    n = 1 << ab
    paths = {}

    def _w(name, text):
        p = os.path.join(outdir, name)
        with open(p, "w") as f:
            f.write(text)
        paths[name] = p

    amp_hex = "\n".join(f"{c:0{(gb + 3) // 4}x}" for c in luts["amp_code"])
    ph_hex = "\n".join(f"{c & ((1 << pb) - 1):0{(pb + 3) // 4}x}"
                       for c in luts["ph_code"])
    _w("dpd_amp.memh", amp_hex + "\n")
    _w("dpd_ph.memh", ph_hex + "\n")

    _w("polar_dpd_lut.v", f"""// polar DPD dual LUT (generated by polartx.export.rtl)
// addr: envelope command [{ab}b] -> amp: predistorted DPA code [{gb}b],
//                                   ph:  AM-PM correction [{pb}b signed, pi-scaled]
module polar_dpd_lut (
    input  wire              clk,
    input  wire [{ab - 1}:0] addr,
    output reg  [{gb - 1}:0] amp,
    output reg  signed [{pb - 1}:0] ph
);
    reg [{gb - 1}:0] rom_amp [0:{n - 1}];
    reg [{pb - 1}:0] rom_ph  [0:{n - 1}];
    initial begin
        $readmemh("dpd_amp.memh", rom_amp);
        $readmemh("dpd_ph.memh", rom_ph);
    end
    always @(posedge clk) begin
        amp <= rom_amp[addr];
        ph  <= $signed(rom_ph[addr]);
    end
endmodule
""")

    golden = "\n".join(f"{i},{a},{p}" for i, (a, p) in
                       enumerate(zip(luts["amp_code"], luts["ph_code"])))
    _w("golden_dpd.csv", golden + "\n")

    _w("tb_polar_dpd_lut.v", f"""// self-checking testbench: sweeps every address, compares to golden CSV
`timescale 1ns/1ps
module tb_polar_dpd_lut;
    reg clk = 0;
    reg [{ab - 1}:0] addr = 0;
    wire [{gb - 1}:0] amp;
    wire signed [{pb - 1}:0] ph;
    polar_dpd_lut dut(.clk(clk), .addr(addr), .amp(amp), .ph(ph));

    integer fd, code, ga, gp, gi, errors, i, r;
    initial begin
        errors = 0;
        fd = $fopen("golden_dpd.csv", "r");
        if (fd == 0) begin $display("FAIL: no golden file"); $finish; end
        for (i = 0; i < {n}; i = i + 1) begin
            r = $fscanf(fd, "%d,%d,%d\\n", gi, ga, gp);
            addr = gi[{ab - 1}:0];
            #1 clk = 1; #1 clk = 0;   // one clock edge
            if (amp !== ga[{gb - 1}:0] || ph !== gp[{pb - 1}:0])
                begin errors = errors + 1;
                $display("MISMATCH @%0d: amp %0d/%0d ph %0d/%0d",
                         gi, amp, ga, ph, gp); end
        end
        if (errors == 0) $display("PASS: {n} vectors, zero mismatches");
        else $display("FAIL: %0d mismatches", errors);
        $finish;
    end
endmodule
""")
    return paths


def efm1_int_golden(phase_words: np.ndarray, n_bits: int,
                    frac_bits: int) -> np.ndarray:
    """Bit-true integer reference of the first-order error-feedback
    quantizer: s = x + err; code = (s >> frac) mod 2^n; err = s & mask."""
    mask = (1 << frac_bits) - 1
    nmod = (1 << n_bits) - 1
    err, out = 0, np.empty(len(phase_words), dtype=np.int64)
    for i, x in enumerate(np.asarray(phase_words, dtype=np.int64)):
        s = int(x) + err
        out[i] = (s >> frac_bits) & nmod
        err = s & mask
    return out


def emit_dtc_dither_rtl(outdir: str, *, n_bits: int = 11,
                        frac_bits: int = 8, n_vec: int = 2048,
                        seed: int = 7) -> dict:
    """DTC code path: phase word -> EFM1-dithered DTC code (sequential
    logic; golden vectors stepped clock-by-clock)."""
    os.makedirs(outdir, exist_ok=True)
    w = n_bits + frac_bits
    rng = np.random.default_rng(seed)
    xw = rng.integers(0, 1 << w, n_vec)
    golden = efm1_int_golden(xw, n_bits, frac_bits)
    paths = {}

    def _w(name, text):
        p = os.path.join(outdir, name)
        with open(p, "w") as f:
            f.write(text)
        paths[name] = p

    _w("dtc_dither.v", f"""// DTC EFM1 dither code path (generated by polartx.export.rtl)
// phase word [{w}b] = code[{n_bits}b].frac[{frac_bits}b] -> dithered DTC code
module dtc_dither (
    input  wire              clk,
    input  wire              rst,
    input  wire [{w - 1}:0]  phase_w,
    output wire [{n_bits - 1}:0] code
);
    reg [{frac_bits - 1}:0] err;
    wire [{w}:0] s = phase_w + err;
    assign code = s[{w - 1}:{frac_bits}];   // mod 2^{n_bits} by truncation
    always @(posedge clk)
        if (rst) err <= 0;
        else     err <= s[{frac_bits - 1}:0];
endmodule
""")
    _w("golden_dither.csv",
       "\n".join(f"{x},{g}" for x, g in zip(xw, golden)) + "\n")
    _w("tb_dtc_dither.v", f"""`timescale 1ns/1ps
module tb_dtc_dither;
    reg clk = 0, rst = 1;
    reg [{w - 1}:0] phase_w = 0;
    wire [{n_bits - 1}:0] code;
    dtc_dither dut(.clk(clk), .rst(rst), .phase_w(phase_w), .code(code));
    integer fd, gx, gc, errors, i, r;
    initial begin
        errors = 0;
        fd = $fopen("golden_dither.csv", "r");
        if (fd == 0) begin $display("FAIL: no golden file"); $finish; end
        #1 clk = 1; #1 clk = 0; rst = 0;   // reset err
        for (i = 0; i < {n_vec}; i = i + 1) begin
            r = $fscanf(fd, "%d,%d\\n", gx, gc);
            phase_w = gx[{w - 1}:0];
            #1;                             // combinational code settles
            if (code !== gc[{n_bits - 1}:0]) begin
                errors = errors + 1;
                $display("MISMATCH @%0d: %0d/%0d", i, code, gc);
            end
            #1 clk = 1; #1 clk = 0;         // register err for next word
        end
        if (errors == 0) $display("PASS: {n_vec} vectors, zero mismatches");
        else $display("FAIL: %0d mismatches", errors);
        $finish;
    end
endmodule
""")
    return paths


def verify_dither_with_iverilog(outdir: str) -> str | None:
    import shutil
    import subprocess
    if shutil.which("iverilog") is None:
        return None
    vvp = os.path.join(outdir, "tb_dither.vvp")
    subprocess.run(["iverilog", "-o", vvp, "dtc_dither.v",
                    "tb_dtc_dither.v"], cwd=outdir, check=True)
    out = subprocess.run(["vvp", os.path.basename(vvp)], cwd=outdir,
                         check=True, capture_output=True, text=True)
    return out.stdout


def verify_with_iverilog(outdir: str) -> str | None:
    """Compile + run the testbench; returns stdout, or None when
    iverilog is not installed."""
    import shutil
    import subprocess
    if shutil.which("iverilog") is None:
        return None
    vvp = os.path.join(outdir, "tb.vvp")
    subprocess.run(["iverilog", "-o", vvp, "polar_dpd_lut.v",
                    "tb_polar_dpd_lut.v"], cwd=outdir, check=True)
    out = subprocess.run(["vvp", os.path.basename(vvp)], cwd=outdir,
                         check=True, capture_output=True, text=True)
    return out.stdout


# ======================================================================
#  DPA segmented thermometer decoder (the amplitude DAC's digital front)
# ======================================================================

def thermo_decode_golden(n_bits: int, n_thermo: int) -> dict:
    """Bit-true reference for the binary -> (thermometer, binary) decode.

    The n_thermo MSBs select how many of the (2^n_thermo - 1) equal
    thermometer segments are enabled; the remaining LSBs pass through as
    binary-weighted cells (mirrors ``code_amplitude_table``'s segmentation).
    """
    if not 0 <= n_thermo <= n_bits:
        raise ValueError("need 0 <= n_thermo <= n_bits")
    n_bin = n_bits - n_thermo
    n_seg = (1 << n_thermo) - 1
    codes = np.arange(1 << n_bits, dtype=np.int64)
    t_cnt = codes >> n_bin                       # segments enabled (0..n_seg)
    # thermometer word = t_cnt low bits set = (1 << t_cnt) - 1.  Kept as a
    # Python big-int list: n_seg can exceed 63 bits, which would overflow
    # int64 (the amplitude DAC routinely has 127 thermo segments).
    thermo_int = [(1 << int(t)) - 1 for t in t_cnt] if n_seg \
        else [0] * len(codes)
    binw = codes & ((1 << n_bin) - 1)
    return {"n_bits": n_bits, "n_thermo": n_thermo, "n_bin": n_bin,
            "n_seg": n_seg, "codes": codes, "thermo_int": thermo_int,
            "bin": binw}


def emit_thermo_decoder_rtl(cfg, outdir: str) -> dict:
    """Combinational binary->thermometer+binary decoder + golden + tb.

    ``cfg`` is a DPAConfig (uses n_bits, n_thermo)."""
    os.makedirs(outdir, exist_ok=True)
    g = thermo_decode_golden(cfg.n_bits, cfg.n_thermo)
    nb, nt, nbin, nseg = (g["n_bits"], g["n_thermo"], g["n_bin"], g["n_seg"])
    n = 1 << nb
    paths = {}

    def _w(name, text):
        p = os.path.join(outdir, name)
        with open(p, "w") as f:
            f.write(text)
        paths[name] = p

    seg_hex_w = max((nseg + 3) // 4, 1)
    bin_hex_w = max((nbin + 3) // 4, 1)
    tw = max(nseg, 1)          # thermo port width (>=1 for a legal port)
    bw = max(nbin, 1)          # binary port width
    # select expressions guarded for the all-binary / all-thermo edge cases
    tsel_decl = (f"    wire [{max(nt, 1) - 1}:0] tsel = code[{nb - 1}:{nbin}];\n"
                 if nseg else "")
    thermo_body = (f"""    genvar g;
    generate for (g = 0; g < {nseg}; g = g + 1)
        assign thermo[g] = (tsel > g);
    endgenerate"""
                   if nseg else "    assign thermo = 1'b0;")
    bin_body = (f"    assign bin = code[{nbin - 1}:0];" if nbin
                else "    assign bin = 1'b0;")
    _w("dpa_thermo_decode.v", f"""// DPA segmented amplitude decoder (generated by polartx.export.rtl)
// code[{nb}b] = thermo_sel[{nt}b].binary[{nbin}b] ->
//   thermo[{nseg}b] (unary, bit g on iff segment g < thermo_sel)
//   bin[{nbin}b]    (binary-weighted LSB cells)
module dpa_thermo_decode (
    input  wire [{nb - 1}:0] code,
    output wire [{tw - 1}:0] thermo,
    output wire [{bw - 1}:0] bin
);
{tsel_decl}{thermo_body}
{bin_body}
endmodule
""")
    # thermometer word can be up to 2^n_thermo-1 bits wide -> emit as hex so
    # the testbench reads it into a wide reg (a Verilog integer is only 32-bit)
    _w("golden_thermo.csv",
       "\n".join(f"{c},{t:0{seg_hex_w}x},{b:0{bin_hex_w}x}" for c, t, b in
                 zip(g["codes"], g["thermo_int"], g["bin"])) + "\n")
    _w("tb_dpa_thermo_decode.v", f"""`timescale 1ns/1ps
module tb_dpa_thermo_decode;
    reg [{nb - 1}:0] code;
    wire [{tw - 1}:0] thermo;
    wire [{bw - 1}:0] bin;
    dpa_thermo_decode dut(.code(code), .thermo(thermo), .bin(bin));
    integer fd, gc, errors, i, r;
    reg [{tw - 1}:0] gt;
    reg [{bw - 1}:0] gb;
    initial begin
        errors = 0;
        fd = $fopen("golden_thermo.csv", "r");
        if (fd == 0) begin $display("FAIL: no golden file"); $finish; end
        for (i = 0; i < {n}; i = i + 1) begin
            r = $fscanf(fd, "%d,%h,%h\\n", gc, gt, gb);
            code = gc[{nb - 1}:0];
            #1;
            if (thermo !== gt || bin !== gb) begin
                errors = errors + 1;
                $display("MISMATCH @%0d: thermo %h/%h bin %h/%h",
                         gc, thermo, gt, bin, gb);
            end
        end
        if (errors == 0) $display("PASS: {n} vectors, zero mismatches");
        else $display("FAIL: %0d mismatches", errors);
        $finish;
    end
endmodule
""")
    return paths


# ======================================================================
#  Polar CFR clip stage (fixed-point envelope peak limiter)
# ======================================================================

def cfr_clip_golden(env_code: np.ndarray, threshold: int) -> np.ndarray:
    """Hard magnitude limiter in the polar domain: env -> min(env, T).

    This is the clip half of iterative clipping-and-filtering; in a polar
    TX it acts directly on the separated envelope word (the phase is
    untouched).  The brick-wall refilter lives in the pulse-shaping path."""
    e = np.asarray(env_code, dtype=np.int64)
    return np.minimum(e, int(threshold))


def emit_cfr_clip_rtl(outdir: str, *, w: int = 12, threshold: int | None = None,
                      n_vec: int = 1024, seed: int = 3) -> dict:
    """Combinational envelope limiter (compare + mux) + golden + tb."""
    os.makedirs(outdir, exist_ok=True)
    if threshold is None:
        threshold = int(0.75 * ((1 << w) - 1))
    rng = np.random.default_rng(seed)
    env = rng.integers(0, 1 << w, n_vec)
    golden = cfr_clip_golden(env, threshold)
    paths = {}

    def _w(name, text):
        p = os.path.join(outdir, name)
        with open(p, "w") as f:
            f.write(text)
        paths[name] = p

    _w("cfr_clip.v", f"""// polar CFR clip stage (generated by polartx.export.rtl)
// envelope peak limiter: env[{w}b] -> min(env, THRESHOLD); clip flag
module cfr_clip #(parameter [{w - 1}:0] THRESHOLD = {threshold}) (
    input  wire [{w - 1}:0] env,
    output wire [{w - 1}:0] env_clip,
    output wire             clipped
);
    assign clipped  = (env > THRESHOLD);
    assign env_clip = clipped ? THRESHOLD : env;
endmodule
""")
    _w("golden_cfr.csv",
       "\n".join(f"{e},{c}" for e, c in zip(env, golden)) + "\n")
    _w("tb_cfr_clip.v", f"""`timescale 1ns/1ps
module tb_cfr_clip;
    reg [{w - 1}:0] env;
    wire [{w - 1}:0] env_clip;
    wire clipped;
    cfr_clip #(.THRESHOLD({threshold})) dut(.env(env), .env_clip(env_clip),
                                            .clipped(clipped));
    integer fd, ge, gc, errors, i, r;
    initial begin
        errors = 0;
        fd = $fopen("golden_cfr.csv", "r");
        if (fd == 0) begin $display("FAIL: no golden file"); $finish; end
        for (i = 0; i < {n_vec}; i = i + 1) begin
            r = $fscanf(fd, "%d,%d\\n", ge, gc);
            env = ge[{w - 1}:0];
            #1;
            if (env_clip !== gc[{w - 1}:0]) begin
                errors = errors + 1;
                $display("MISMATCH @%0d: %0d/%0d", ge, env_clip, gc);
            end
        end
        if (errors == 0) $display("PASS: {n_vec} vectors, zero mismatches");
        else $display("FAIL: %0d mismatches", errors);
        $finish;
    end
endmodule
""")
    return paths


# ======================================================================
#  DTC phase-accumulator datapath (open-loop DDS-style phase generation)
# ======================================================================

def phase_acc_golden(finc: np.ndarray, w: int) -> np.ndarray:
    """Modulo-2^w phase accumulator: acc[n] = (acc[n-1] + finc[n]) mod 2^w,
    registered (acc starts at 0, output is the value after adding finc[n])."""
    mask = (1 << w) - 1
    acc, out = 0, np.empty(len(finc), dtype=np.int64)
    for i, f in enumerate(np.asarray(finc, dtype=np.int64)):
        acc = (acc + int(f)) & mask
        out[i] = acc
    return out


def emit_phase_acc_rtl(outdir: str, *, w: int = 16, n_vec: int = 2048,
                       seed: int = 11) -> dict:
    """Sequential phase accumulator (the DTC/DDS phase datapath) + golden."""
    os.makedirs(outdir, exist_ok=True)
    rng = np.random.default_rng(seed)
    finc = rng.integers(0, 1 << w, n_vec)
    golden = phase_acc_golden(finc, w)
    paths = {}

    def _w(name, text):
        p = os.path.join(outdir, name)
        with open(p, "w") as f:
            f.write(text)
        paths[name] = p

    _w("dtc_phase_acc.v", f"""// DTC phase-accumulator datapath (generated by polartx.export.rtl)
// frequency command finc[{w}b] -> wrapped phase word phase[{w}b] (mod 2^{w})
module dtc_phase_acc (
    input  wire              clk,
    input  wire              rst,
    input  wire [{w - 1}:0]  finc,
    output reg  [{w - 1}:0]  phase
);
    always @(posedge clk)
        if (rst) phase <= 0;
        else     phase <= phase + finc;   // natural mod-2^{w} wrap
endmodule
""")
    _w("golden_phase_acc.csv",
       "\n".join(f"{f},{p}" for f, p in zip(finc, golden)) + "\n")
    _w("tb_dtc_phase_acc.v", f"""`timescale 1ns/1ps
module tb_dtc_phase_acc;
    reg clk = 0, rst = 1;
    reg [{w - 1}:0] finc = 0;
    wire [{w - 1}:0] phase;
    dtc_phase_acc dut(.clk(clk), .rst(rst), .finc(finc), .phase(phase));
    integer fd, gf, gp, errors, i, r;
    initial begin
        errors = 0;
        fd = $fopen("golden_phase_acc.csv", "r");
        if (fd == 0) begin $display("FAIL: no golden file"); $finish; end
        #1 clk = 1; #1 clk = 0; rst = 0;   // clear accumulator
        for (i = 0; i < {n_vec}; i = i + 1) begin
            r = $fscanf(fd, "%d,%d\\n", gf, gp);
            finc = gf[{w - 1}:0];
            #1 clk = 1; #1 clk = 0;         // accumulate one sample
            if (phase !== gp[{w - 1}:0]) begin
                errors = errors + 1;
                $display("MISMATCH @%0d: %0d/%0d", i, phase, gp);
            end
        end
        if (errors == 0) $display("PASS: {n_vec} vectors, zero mismatches");
        else $display("FAIL: %0d mismatches", errors);
        $finish;
    end
endmodule
""")
    return paths


# ======================================================================
#  Verilog-AMS / RNM (wreal) model of the DPA — the digital<->analog bridge
# ======================================================================

def _rapp_vams(p: float, drive: float) -> str:
    fs = drive / (1.0 + drive ** (2.0 * p)) ** (1.0 / (2.0 * p))
    return (f"        x = {drive!r} * r;\n"
            f"        y = x / pow(1.0 + pow(x, {2.0 * p!r}), {1.0 / (2.0 * p)!r});\n"
            f"        r_out = y / {fs!r};")


def emit_dpa_rnm_vams(dpa, outdir: str) -> dict:
    """Emit a Verilog-AMS ``wreal`` real-number model of the DPA.

    The RNM consumes the digital decoder's per-code amplitude (as a real
    LUT baked from the mismatched unit-cell array) and applies the AM-AM
    and AM-PM laws in real math, driving a behavioural RF amplitude/phase.
    This is the AMS co-simulation bridge: the synthesizable digital blocks
    (thermo decoder, CFR clip, phase datapath) drive this analog PA model.

    Requires a Verilog-AMS simulator (spectre/xcelium/questa-AMS) to run --
    it is NOT iverilog-compilable.  The baked LUT is verified against the
    Python DPA tables (dpa_rnm_selfcheck) so the emitted model is bit-exact
    to the behavioral reference at the code level.
    """
    os.makedirs(outdir, exist_ok=True)
    cfg = dpa.cfg
    n = cfg.n_codes
    amp = dpa.amp_table
    ph = dpa.phase_table
    paths = {}

    def _w(name, text):
        p = os.path.join(outdir, name)
        with open(p, "w") as f:
            f.write(text)
        paths[name] = p

    # bake per-code amplitude (normalized, post AM-AM) and AM-PM (rad) as
    # real memh LUTs read at elaboration
    _w("dpa_amp_real.memh",
       "\n".join(f"{a:.9e}" for a in amp) + "\n")
    _w("dpa_ampm_real.memh",
       "\n".join(f"{p:.9e}" for p in ph) + "\n")

    _w("dpa_rnm.vams", f"""// Verilog-AMS real-number model of the digital PA (generated by
// polartx.export.rtl).  wreal amplitude/phase vs the {cfg.n_bits}-bit code.
// Consumes the amplitude code (post-decode); the mismatched unit-cell
// summation, AM-AM ({cfg.amam!r}) and AM-PM are baked into the real LUTs
// dpa_amp_real.memh / dpa_ampm_real.memh so this model is code-exact to the
// polartx behavioral DPA.  Requires a Verilog-AMS simulator (not iverilog).
`include "disciplines.vams"
module dpa_rnm (code, amp_out, phase_out);
    parameter integer NB = {cfg.n_bits};
    parameter integer N  = {n};
    input  [NB-1:0] code;
    output amp_out, phase_out;
    wreal  amp_out, phase_out;

    real amp_lut [0:N-1];
    real ph_lut  [0:N-1];
    initial begin
        $readmemh("dpa_amp_real.memh", amp_lut);
        $readmemh("dpa_ampm_real.memh", ph_lut);
    end
    assign amp_out   = amp_lut[code];   // normalized RF amplitude (fs = 1)
    assign phase_out = ph_lut[code];    // AM-PM [rad]
endmodule
""")
    # AMS co-sim testbench stub wiring the digital decoder to the RNM PA
    _w("tb_dpa_ams.vams", f"""// AMS co-simulation stub: digital decoder + code path driving the RNM PA.
// Elaborate with the synthesizable RTL (dpa_thermo_decode.v etc.) under a
// Verilog-AMS simulator.  Sweeps all {n} codes and prints amp/phase.
`timescale 1ns/1ps
module tb_dpa_ams;
    reg  [{cfg.n_bits - 1}:0] code;
    wreal amp, phase;
    dpa_rnm dut(.code(code), .amp_out(amp), .phase_out(phase));
    integer i;
    initial begin
        for (i = 0; i < {n}; i = i + 1) begin
            code = i[{cfg.n_bits - 1}:0];
            #1 $display("code %0d  amp %g  ampm_rad %g", i, amp, phase);
        end
        $finish;
    end
endmodule
""")
    return paths


def dpa_rnm_selfcheck(dpa, outdir: str) -> dict:
    """Verify the baked RNM LUTs reproduce the DPA tables at zero tolerance
    (the AMS analogue of the iverilog golden check)."""
    amp = np.loadtxt(os.path.join(outdir, "dpa_amp_real.memh"))
    ph = np.loadtxt(os.path.join(outdir, "dpa_ampm_real.memh"))
    amp_err = float(np.max(np.abs(amp - dpa.amp_table)))
    ph_err = float(np.max(np.abs(ph - dpa.phase_table)))
    return {"amp_max_err": amp_err, "ph_max_err": ph_err,
            "ok": amp_err < 1e-8 and ph_err < 1e-8}


# ---------------------------------------------------------------- verify

def _iverilog_run(outdir: str, sources: list[str], top_vvp: str) -> str | None:
    import shutil
    import subprocess
    if shutil.which("iverilog") is None:
        return None
    subprocess.run(["iverilog", "-g2012", "-o", top_vvp, *sources],
                   cwd=outdir, check=True)
    out = subprocess.run(["vvp", top_vvp], cwd=outdir, check=True,
                        capture_output=True, text=True)
    return out.stdout


def verify_thermo_decoder(outdir: str) -> str | None:
    return _iverilog_run(outdir, ["dpa_thermo_decode.v",
                                  "tb_dpa_thermo_decode.v"], "tb_thermo.vvp")


def verify_cfr_clip(outdir: str) -> str | None:
    return _iverilog_run(outdir, ["cfr_clip.v", "tb_cfr_clip.v"], "tb_cfr.vvp")


def verify_phase_acc(outdir: str) -> str | None:
    return _iverilog_run(outdir, ["dtc_phase_acc.v", "tb_dtc_phase_acc.v"],
                         "tb_phase_acc.vvp")


def emit_datapath(dpa, outdir: str, *, dpd=None) -> dict:
    """Emit the full digital polar-TX datapath + AMS PA model in one dir:
    CFR clip -> DPD LUT (optional) -> DPA thermo decoder -> RNM DPA, plus
    the DTC phase-accumulator datapath.  Returns all written paths."""
    paths = {}
    paths.update(emit_cfr_clip_rtl(outdir))
    paths.update(emit_phase_acc_rtl(outdir))
    paths.update(emit_thermo_decoder_rtl(dpa.cfg, outdir))
    paths.update(emit_dpa_rnm_vams(dpa, outdir))
    if dpd is not None:
        paths.update(emit_dpd_rtl(quantize_dpd_luts(dpd), outdir))
    return paths
