"""RTL export: the polar-DPD dual LUT as synthesizable Verilog.

The AM-AM inverse and AM-PM correction LUTs are the polar TX's
signature digital block.  Export quantizes them to hardware formats
(unsigned amplitude, signed phase in pi-scaled two's complement),
emits a $readmemh ROM module + a self-checking testbench, and writes
golden vectors from the bit-true Python quantization — the pllsim
export convention: RTL verified against Python at zero tolerance
(iverilog, skipped when unavailable).
"""
from __future__ import annotations

import os

import numpy as np


def quantize_dpd_luts(dpd, *, addr_bits: int = 8, amp_bits: int = 12,
                      ph_bits: int = 14) -> dict:
    """Sample the PolarDPD LUTs on a 2^addr_bits grid and quantize.

    amp: unsigned, full scale = (2^amp_bits - 1).
    phase: signed two's complement, [-pi, pi) mapped to the full range.
    """
    n = 1 << addr_bits
    x = np.arange(n) / (n - 1)
    amp, ph = dpd.predistort(x)
    amp_code = np.clip(np.rint(amp * ((1 << amp_bits) - 1)),
                       0, (1 << amp_bits) - 1).astype(np.int64)
    half = 1 << (ph_bits - 1)
    ph_code = np.clip(np.rint(ph / np.pi * half), -half, half - 1
                      ).astype(np.int64)
    return {"addr_bits": addr_bits, "amp_bits": amp_bits,
            "ph_bits": ph_bits, "amp_code": amp_code, "ph_code": ph_code,
            "amp_float": amp_code / ((1 << amp_bits) - 1),
            "ph_float": ph_code * np.pi / half}


def emit_dpd_rtl(luts: dict, outdir: str) -> dict:
    """Write polar_dpd_lut.v, ROM .memh files, golden CSV, testbench."""
    os.makedirs(outdir, exist_ok=True)
    ab, gb, pb = luts["addr_bits"], luts["amp_bits"], luts["ph_bits"]
    n = 1 << ab
    paths = {}

    def _w(name, text):
        p = os.path.join(outdir, name)
        with open(p, "w") as f:
            f.write(text)
        paths[name] = p

    amp_hex = "\n".join(f"{c:0{(gb + 3) // 4}x}" for c in luts["amp_code"])
    ph_hex = "\n".join(f"{c & ((1 << pb) - 1):0{(pb + 3) // 4}x}"
                       for c in luts["ph_code"])
    _w("dpd_amp.memh", amp_hex + "\n")
    _w("dpd_ph.memh", ph_hex + "\n")

    _w("polar_dpd_lut.v", f"""// polar DPD dual LUT (generated by polartx.export.rtl)
// addr: envelope command [{ab}b] -> amp: predistorted DPA code [{gb}b],
//                                   ph:  AM-PM correction [{pb}b signed, pi-scaled]
module polar_dpd_lut (
    input  wire              clk,
    input  wire [{ab - 1}:0] addr,
    output reg  [{gb - 1}:0] amp,
    output reg  signed [{pb - 1}:0] ph
);
    reg [{gb - 1}:0] rom_amp [0:{n - 1}];
    reg [{pb - 1}:0] rom_ph  [0:{n - 1}];
    initial begin
        $readmemh("dpd_amp.memh", rom_amp);
        $readmemh("dpd_ph.memh", rom_ph);
    end
    always @(posedge clk) begin
        amp <= rom_amp[addr];
        ph  <= $signed(rom_ph[addr]);
    end
endmodule
""")

    golden = "\n".join(f"{i},{a},{p}" for i, (a, p) in
                       enumerate(zip(luts["amp_code"], luts["ph_code"])))
    _w("golden_dpd.csv", golden + "\n")

    _w("tb_polar_dpd_lut.v", f"""// self-checking testbench: sweeps every address, compares to golden CSV
`timescale 1ns/1ps
module tb_polar_dpd_lut;
    reg clk = 0;
    reg [{ab - 1}:0] addr = 0;
    wire [{gb - 1}:0] amp;
    wire signed [{pb - 1}:0] ph;
    polar_dpd_lut dut(.clk(clk), .addr(addr), .amp(amp), .ph(ph));

    integer fd, code, ga, gp, gi, errors, i, r;
    initial begin
        errors = 0;
        fd = $fopen("golden_dpd.csv", "r");
        if (fd == 0) begin $display("FAIL: no golden file"); $finish; end
        for (i = 0; i < {n}; i = i + 1) begin
            r = $fscanf(fd, "%d,%d,%d\\n", gi, ga, gp);
            addr = gi[{ab - 1}:0];
            #1 clk = 1; #1 clk = 0;   // one clock edge
            if (amp !== ga[{gb - 1}:0] || ph !== gp[{pb - 1}:0])
                begin errors = errors + 1;
                $display("MISMATCH @%0d: amp %0d/%0d ph %0d/%0d",
                         gi, amp, ga, ph, gp); end
        end
        if (errors == 0) $display("PASS: {n} vectors, zero mismatches");
        else $display("FAIL: %0d mismatches", errors);
        $finish;
    end
endmodule
""")
    return paths


def verify_with_iverilog(outdir: str) -> str | None:
    """Compile + run the testbench; returns stdout, or None when
    iverilog is not installed."""
    import shutil
    import subprocess
    if shutil.which("iverilog") is None:
        return None
    vvp = os.path.join(outdir, "tb.vvp")
    subprocess.run(["iverilog", "-o", vvp, "polar_dpd_lut.v",
                    "tb_polar_dpd_lut.v"], cwd=outdir, check=True)
    out = subprocess.run(["vvp", os.path.basename(vvp)], cwd=outdir,
                         check=True, capture_output=True, text=True)
    return out.stdout
